package com.liqiang.gradle.gradleboot.mapper;
import java.util.List;
import java.util.Date;
import org.apache.ibatis.annotations.Param;

import com.liqiang.gradle.gradleboot.model.CusCustomerInfo;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

@Component(value = "cusCustomerInfoMapper")
public interface CusCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    int insert(CusCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    int insertSelective(CusCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    CusCustomerInfo selectByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CusCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CusCustomerInfo record);

    int updateCustomernamebycid(@Param("updatedCustomername")String updatedCustomername,@Param("cid")Long cid);

    Integer councilwomenIbid(@Param("cid")Long cid);


    List<CusCustomerInfo> findListForCustomet(@Param("customeraccount")String customeraccount,@Param("cid")Long cid,@Param("createdate")Date createdate);






}